install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.57.0/hugo_0.57.0_Linux-64bit.deb
  - sudo dpkg -i hugo_0.57.0_Linux-64bit.deb

script:
  - hugo

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  target_branch: master
  github_token: $GITHUB_TOKEN
  fqdn: www.alivychan.me
  on:
    branch: source